<?php
/**
 * Project: TP messaging service
 * User: george
 * Date: 14.09.17
 */

namespace NewInventor\DataStructure\Accessory;


class CountriesAndRegions
{
    //dependent
    const ANTARCTICA = 10;
    const AMERICAN_SAMOA = 16;
    const BERMUDA = 60;
    const BOUVET_ISLAND = 74;
    const BRITISH_INDIAN_OCEAN_TERRITORY = 86;
    const BRITISH_VIRGIN_ISLANDS = 92;
    const CAYMAN_ISLANDS = 136;
    const TAIWAN = 158;
    const CHRISTMAS_ISLAND = 162;
    const COCOS_ISLANDS = 166;
    const MAYOTTE = 175;
    const COOK_ISLANDS = 184;
    const FAROE_ISLANDS = 234;
    const FALKLAND_ISLANDS = 238;
    const SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 239;
    const ALAND_ISLANDS = 248;
    const FRENCH_GUIANA = 254;
    const FRENCH_POLYNESIA = 258;
    const FRENCH_SOUTHERN_TERRITORIES = 260;
    const PALESTINE_STATE_OF = 275;
    const GIBRALTAR = 292;
    const GREENLAND = 304;
    const GUADELOUPE = 312;
    const GUAM = 316;
    const HEARD_ISLAND_AND_MC_DONALD_ISLANDS = 334;
    const HONG_KONG = 344;
    const MACAO = 446;
    const MARTINIQUE = 474;
    const MONTSERRAT = 500;
    const CURACAO = 531;
    const ARUBA = 533;
    const DUTCH_SINT_MAARTEN = 534;
    const BONAIRE_SINT_EUSTATIUS_AND_SABA = 535;
    const NEW_CALEDONIA = 540;
    const NIUE = 570;
    const NORFOLK_ISLAND = 574;
    const NORTHERN_MARIANA_ISLANDS = 580;
    const UNITED_STATES_MINOR_OUTLYING_ISLANDS = 581;
    const PITCAIRN = 612;
    const PUERTO_RICO = 630;
    const REUNION = 638;
    const SAINT_BARTHELEMY = 652;
    const SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = 654;
    const ANGUILLA = 660;
    const FRENCH_SAINT_MARTIN = 663;
    const SAINT_PIERRE_AND_MIQUELON = 666;
    const WESTERN_SAHARA = 732;
    const SVALBARD_AND_JAN_MAYEN = 744;
    const TOKELAU = 772;
    const TURKS_AND_CAICOS_ISLANDS = 796;
    const GUERNSEY = 831;
    const JERSEY = 832;
    const ISLE_OF_MAN = 833;
    const US_VIRGIN_ISLANDS = 850;
    const WALLIS_AND_FUTUNA = 876;
    // independent
    const AFGHANISTAN = 4;
    const ALBANIA = 8;
    const ALGERIA = 12;
    const ANDORRA = 20;
    const ANGOLA = 24;
    const ANTIGUA_AND_BARBUDA = 28;
    const AZERBAIJAN = 31;
    const ARGENTINA = 32;
    const AUSTRALIA = 36;
    const AUSTRIA = 40;
    const BAHAMAS = 44;
    const BAHRAIN = 48;
    const BANGLADESH = 50;
    const ARMENIA = 51;
    const BARBADOS = 52;
    const BELGIUM = 56;
    const BHUTAN = 64;
    const BOLIVIA = 68;
    const BOSNIA_AND_HERZEGOVINA = 70;
    const BOTSWANA = 72;
    const BRAZIL = 76;
    const BELIZE = 84;
    const SOLOMON_ISLANDS = 90;
    const BRUNEI_DARUSSALAM = 96;
    const BULGARIA = 100;
    const MYANMAR = 104;
    const BURUNDI = 108;
    const BELARUS = 112;
    const CAMBODIA = 116;
    const CAMEROON = 120;
    const CANADA = 124;
    const CABO_VERDE = 132;
    const CENTRAL_AFRICAN_REPUBLIC = 140;
    const SRI_LANKA = 144;
    const CHAD = 148;
    const CHILE = 152;
    const CHINA = 156;
    const COLOMBIA = 170;
    const COMOROS = 174;
    const CONGO = 178;
    const CONGO_DEMOCRATIC_REPUBLIC = 180;
    const COSTA_RICA = 188;
    const CROATIA = 191;
    const CUBA = 192;
    const CYPRUS = 196;
    const CZECHIA = 203;
    const BENIN = 204;
    const DENMARK = 208;
    const DOMINICA = 212;
    const DOMINICAN_REPUBLIC = 214;
    const ECUADOR = 218;
    const EL_SALVADOR = 222;
    const EQUATORIAL_GUINEA = 226;
    const ETHIOPIA = 231;
    const ERITREA = 232;
    const ESTONIA = 233;
    const FIJI = 242;
    const FINLAND = 246;
    const FRANCE = 250;
    const DJIBOUTI = 262;
    const GABON = 266;
    const GEORGIA = 268;
    const GAMBIA = 270;
    const GERMANY = 276;
    const GHANA = 288;
    const KIRIBATI = 296;
    const GREECE = 300;
    const GRENADA = 308;
    const GUATEMALA = 320;
    const GUINEA = 324;
    const GUYANA = 328;
    const HAITI = 332;
    const HOLY_SEE = 336;
    const HONDURAS = 340;
    const HUNGARY = 348;
    const ICELAND = 352;
    const INDIA = 356;
    const INDONESIA = 360;
    const IRAN = 364;
    const IRAQ = 368;
    const IRELAND = 372;
    const ISRAEL = 376;
    const ITALY = 380;
    const COTE_D_IVOIRE = 384;
    const JAMAICA = 388;
    const JAPAN = 392;
    const KAZAKHSTAN = 398;
    const JORDAN = 400;
    const KENYA = 404;
    const KOREA_PEOPLES_DEMOCRATIC_REPUBLIC = 408;
    const KOREA_REPUBLIC = 410;
    const KUWAIT = 414;
    const KYRGYZSTAN = 417;
    const LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 418;
    const LEBANON = 422;
    const LESOTHO = 426;
    const LATVIA = 428;
    const LIBERIA = 430;
    const LIBYA = 434;
    const LIECHTENSTEIN = 438;
    const LITHUANIA = 440;
    const LUXEMBOURG = 442;
    const MADAGASCAR = 450;
    const MALAWI = 454;
    const MALAYSIA = 458;
    const MALDIVES = 462;
    const MALI = 466;
    const MALTA = 470;
    const MAURITANIA = 478;
    const MAURITIUS = 480;
    const MEXICO = 484;
    const MONACO = 492;
    const MONGOLIA = 496;
    const MOLDOVA = 498;
    const MONTENEGRO = 499;
    const MOROCCO = 504;
    const MOZAMBIQUE = 508;
    const OMAN = 512;
    const NAMIBIA = 516;
    const NAURU = 520;
    const NEPAL = 524;
    const NETHERLANDS = 528;
    const VANUATU = 548;
    const NEW_ZEALAND = 554;
    const NICARAGUA = 558;
    const NIGER = 562;
    const NIGERIA = 566;
    const NORWAY = 578;
    const MICRONESIA = 583;
    const MARSHALL_ISLANDS = 584;
    const PALAU = 585;
    const PAKISTAN = 586;
    const PANAMA = 591;
    const PAPUA_NEW_GUINEA = 598;
    const PARAGUAY = 600;
    const PERU = 604;
    const PHILIPPINES = 608;
    const POLAND = 616;
    const PORTUGAL = 620;
    const GUINEA_BISSAU = 624;
    const TIMOR_LESTE = 626;
    const QATAR = 634;
    const ROMANIA = 642;
    const RUSSIAN_FEDERATION = 643;
    const RWANDA = 646;
    const SAINT_KITTS_AND_NEVIS = 659;
    const SAINT_LUCIA = 662;
    const SAINT_VINCENT_AND_THE_GRENADINES = 670;
    const SAN_MARINO = 674;
    const SAO_TOME_AND_PRINCIPE = 678;
    const SAUDI_ARABIA = 682;
    const SENEGAL = 686;
    const SERBIA = 688;
    const SEYCHELLES = 690;
    const SIERRA_LEONE = 694;
    const SINGAPORE = 702;
    const SLOVAKIA = 703;
    const VIET_NAM = 704;
    const SLOVENIA = 705;
    const SOMALIA = 706;
    const SOUTH_AFRICA = 710;
    const ZIMBABWE = 716;
    const SPAIN = 724;
    const SOUTH_SUDAN = 728;
    const SUDAN = 729;
    const SURINAME = 740;
    const SWAZILAND = 748;
    const SWEDEN = 752;
    const SWITZERLAND = 756;
    const SYRIAN_ARAB_REPUBLIC = 760;
    const TAJIKISTAN = 762;
    const THAILAND = 764;
    const TOGO = 768;
    const TONGA = 776;
    const TRINIDAD_AND_TOBAGO = 780;
    const UNITED_ARAB_EMIRATES = 784;
    const TUNISIA = 788;
    const TURKEY = 792;
    const TURKMENISTAN = 795;
    const TUVALU = 798;
    const UGANDA = 800;
    const UKRAINE = 804;
    const MACEDONIA = 807;
    const EGYPT = 818;
    const UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND = 826;
    const TANZANIA = 834;
    const UNITED_STATES_OF_AMERICA = 840;
    const BURKINA_FASO = 854;
    const URUGUAY = 858;
    const UZBEKISTAN = 860;
    const VENEZUELA = 862;
    const SAMOA = 882;
    const YEMEN = 887;
    const ZAMBIA = 894;
    //not in iso
    const ABKHAZIA = 895;
    //regions
    const RUSSIAN_FEDERATION_RESPUBLIKA_ADYGEYA = 'RU-AD'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_ALTAY = 'RU-AL'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_BASHKORTOSTAN = 'RU-BA'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_BURYATIYA = 'RU-BU'; //republic
    const RUSSIAN_FEDERATION_CHECHENSKAYA_RESPUBLIKA = 'RU-CE'; //republic
    const RUSSIAN_FEDERATION_CHUVASHSKAYA_RESPUBLIKA = 'RU-CU'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_DAGESTAN = 'RU-DA'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_INGUSHETIYA = 'RU-IN'; //republic
    const RUSSIAN_FEDERATION_KABARDINO_BALKARSKAYA_RESPUBLIKA = 'RU-KB'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_KALMYKIYA = 'RU-KL'; //republic
    const RUSSIAN_FEDERATION_KARACHAYEVO_CHERKESSKAYA_RESPUBLIKA = 'RU-KC'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_KARELIYA = 'RU-KR'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_KHAKASIYA = 'RU-KK'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_KOMI = 'RU-KO'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_MARIY_EL = 'RU-ME'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_MORDOVIYA = 'RU-MO'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_SAKHA_YAKUTIYA = 'RU-SA'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_SEVERNAYA_OSETIYA_ALANIYA = 'RU-SE'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_TATARSTAN = 'RU-TA'; //republic
    const RUSSIAN_FEDERATION_RESPUBLIKA_TYVA_ = 'RU-TY'; //republic
    const RUSSIAN_FEDERATION_UDMURTSKAYA_RESPUBLIKA = 'RU-UD'; //republic
    const RUSSIAN_FEDERATION_ALTAYSKIY_KRAY = 'RU-ALT'; //administrative territory
    const RUSSIAN_FEDERATION_KAMCHATSKIY_KRAY = 'RU-KAM'; //administrative territory
    const RUSSIAN_FEDERATION_KHABAROVSKIY_KRAY = 'RU-KHA'; //administrative territory
    const RUSSIAN_FEDERATION_KRASNODARSKIY_KRAY = 'RU-KDA'; //administrative territory
    const RUSSIAN_FEDERATION_KRASNOYARSKIY_KRAY = 'RU-KYA'; //administrative territory
    const RUSSIAN_FEDERATION_PERMSKIY_KRAY = 'RU-PER'; //administrative territory
    const RUSSIAN_FEDERATION_PRIMORSKIY_KRAY = 'RU-PRI'; //administrative territory
    const RUSSIAN_FEDERATION_STAVROPOLSKIY_KRAY = 'RU-STA'; //administrative territory
    const RUSSIAN_FEDERATION_ZABAYKALSKIY_KRAY = 'RU-ZAB'; //administrative territory
    const RUSSIAN_FEDERATION_AMURSKAYA_OBLAST = 'RU-AMU'; //administrative region
    const RUSSIAN_FEDERATION_ARKHANGELSKAYA_OBLAST = 'RU-ARK'; //administrative region
    const RUSSIAN_FEDERATION_ASTRAKHANSKAYA_OBLAST = 'RU-AST'; //administrative region
    const RUSSIAN_FEDERATION_BELGORODSKAYA_OBLAST = 'RU-BEL'; //administrative region
    const RUSSIAN_FEDERATION_BRYANSKAYA_OBLAST = 'RU-BRY'; //administrative region
    const RUSSIAN_FEDERATION_CHELYABINSKAYA_OBLAST = 'RU-CHE'; //administrative region
    const RUSSIAN_FEDERATION_IRKUTSKAYA_OBLAST = 'RU-IRK'; //administrative region
    const RUSSIAN_FEDERATION_IVANOVSKAYA_OBLAST = 'RU-IVA'; //administrative region
    const RUSSIAN_FEDERATION_KALININGRADSKAYA_OBLAST = 'RU-KGD'; //administrative region
    const RUSSIAN_FEDERATION_KALUZHSKAYA_OBLAST = 'RU-KLU'; //administrative region
    const RUSSIAN_FEDERATION_KEMEROVSKAYA_OBLAST = 'RU-KEM'; //administrative region
    const RUSSIAN_FEDERATION_KIROVSKAYA_OBLAST = 'RU-KIR'; //administrative region
    const RUSSIAN_FEDERATION_KOSTROMSKAYA_OBLAST = 'RU-KOS'; //administrative region
    const RUSSIAN_FEDERATION_KURGANSKAYA_OBLAST = 'RU-KGN'; //administrative region
    const RUSSIAN_FEDERATION_KURSKAYA_OBLAST = 'RU-KRS'; //administrative region
    const RUSSIAN_FEDERATION_LENINGRADSKAYA_OBLAST = 'RU-LEN'; //administrative region
    const RUSSIAN_FEDERATION_LIPETSKAYA_OBLAST = 'RU-LIP'; //administrative region
    const RUSSIAN_FEDERATION_MAGADANSKAYA_OBLAST = 'RU-MAG'; //administrative region
    const RUSSIAN_FEDERATION_MOSKOVSKAYA_OBLAST = 'RU-MOS'; //administrative region
    const RUSSIAN_FEDERATION_MURMANSKAYA_OBLAST = 'RU-MUR'; //administrative region
    const RUSSIAN_FEDERATION_NIZHEGORODSKAYA_OBLAST = 'RU-NIZ'; //administrative region
    const RUSSIAN_FEDERATION_NOVGORODSKAYA_OBLAST = 'RU-NGR'; //administrative region
    const RUSSIAN_FEDERATION_NOVOSIBIRSKAYA_OBLAST = 'RU-NVS'; //administrative region
    const RUSSIAN_FEDERATION_OMSKAYA_OBLAST = 'RU-OMS'; //administrative region
    const RUSSIAN_FEDERATION_ORENBURGSKAYA_OBLAST = 'RU-ORE'; //administrative region
    const RUSSIAN_FEDERATION_ORLOVSKAYA_OBLAST = 'RU-ORL'; //administrative region
    const RUSSIAN_FEDERATION_PENZENSKAYA_OBLAST = 'RU-PNZ'; //administrative region
    const RUSSIAN_FEDERATION_PSKOVSKAYA_OBLAST = 'RU-PSK'; //administrative region
    const RUSSIAN_FEDERATION_ROSTOVSKAYA_OBLAST = 'RU-ROS'; //administrative region
    const RUSSIAN_FEDERATION_RYAZANSKAYA_OBLAST = 'RU-RYA'; //administrative region
    const RUSSIAN_FEDERATION_SAKHALINSKAYA_OBLAST = 'RU-SAK'; //administrative region
    const RUSSIAN_FEDERATION_SAMARSKAYA_OBLAST = 'RU-SAM'; //administrative region
    const RUSSIAN_FEDERATION_SARATOVSKAYA_OBLAST = 'RU-SAR'; //administrative region
    const RUSSIAN_FEDERATION_SMOLENSKAYA_OBLAST = 'RU-SMO'; //administrative region
    const RUSSIAN_FEDERATION_SVERDLOVSKAYA_OBLAST = 'RU-SVE'; //administrative region
    const RUSSIAN_FEDERATION_TAMBOVSKAYA_OBLAST = 'RU-TAM'; //administrative region
    const RUSSIAN_FEDERATION_TOMSKAYA_OBLAST = 'RU-TOM'; //administrative region
    const RUSSIAN_FEDERATION_TULSKAYA_OBLAST = 'RU-TUL'; //administrative region
    const RUSSIAN_FEDERATION_TVERSKAYA_OBLAST = 'RU-TVE'; //administrative region
    const RUSSIAN_FEDERATION_TYUMENSKAYA_OBLAST = 'RU-TYU'; //administrative region
    const RUSSIAN_FEDERATION_ULYANOVSKAYA_OBLAST = 'RU-ULY'; //administrative region
    const RUSSIAN_FEDERATION_VLADIMIRSKAYA_OBLAST = 'RU-VLA'; //administrative region
    const RUSSIAN_FEDERATION_VOLGOGRADSKAYA_OBLAST = 'RU-VGG'; //administrative region
    const RUSSIAN_FEDERATION_VOLOGODSKAYA_OBLAST = 'RU-VLG'; //administrative region
    const RUSSIAN_FEDERATION_VORONEZHSKAYA_OBLAST = 'RU-VOR'; //administrative region
    const RUSSIAN_FEDERATION_YAROSLAVSKAYA_OBLAST = 'RU-YAR'; //administrative region
    const RUSSIAN_FEDERATION_MOSKVA = 'RU-MOW'; //autonomous city
    const RUSSIAN_FEDERATION_SANKT_PETERBURG = 'RU-SPE'; //autonomous city
    const RUSSIAN_FEDERATION_YEVREYSKAYA_AVTONOMNAYA_OBLAST = 'RU-YEV'; //autonomous region
    const RUSSIAN_FEDERATION_CHUKOTSKIY_AVTONOMNYY_OKRUG = 'RU-CHU'; //autonomous district
    const RUSSIAN_FEDERATION_KHANTY_MANSIYSKIY_AVTONOMNYY_OKRUG_YUGRA = 'RU-KHM'; //autonomous district
    const RUSSIAN_FEDERATION_NENETSKIY_AVTONOMNYY_OKRUG = 'RU-NEN'; //autonomous district
    const RUSSIAN_FEDERATION_YAMALO_NENETSKIY_AVTONOMNYY_OKRUG = 'RU-YAN'; //autonomous district
    const GEORGIA_ABKHAZIA = 'GE-AB'; //autonomous republic
    const GEORGIA_AJARIA = 'GE-AJ'; //autonomous republic
    const GEORGIA_TBILISI = 'GE-TB'; //city
    const GEORGIA_GURIA = 'GE-GU'; //region
    const GEORGIA_IMERETI = 'GE-IM'; //region
    const GEORGIA_K_AKHETI = 'GE-KA'; //region
    const GEORGIA_KVEMO_KARTLI = 'GE-KK'; //region
    const GEORGIA_MTSKHETA_MTIANETI = 'GE-MM'; //region
    const GEORGIA_RACH_A_LECHKHUMI_KVEMO_SVANETI = 'GE-RL'; //region
    const GEORGIA_SAMEGRELO_ZEMO_SVANETI = 'GE-SZ'; //region
    const GEORGIA_SAMTSKHE_JAVAKHETI = 'GE-SJ'; //region
    const GEORGIA_SHIDA_KARTLI = 'GE-SK'; //region
    public static $independentNum = [
        self::ABKHAZIA                                             => self::ABKHAZIA,
        self::AFGHANISTAN                                          => self::AFGHANISTAN,
        self::ALBANIA                                              => self::ALBANIA,
        self::ALGERIA                                              => self::ALGERIA,
        self::ANDORRA                                              => self::ANDORRA,
        self::ANGOLA                                               => self::ANGOLA,
        self::ANTIGUA_AND_BARBUDA                                  => self::ANTIGUA_AND_BARBUDA,
        self::AZERBAIJAN                                           => self::AZERBAIJAN,
        self::ARGENTINA                                            => self::ARGENTINA,
        self::AUSTRALIA                                            => self::AUSTRALIA,
        self::AUSTRIA                                              => self::AUSTRIA,
        self::BAHAMAS                                              => self::BAHAMAS,
        self::BAHRAIN                                              => self::BAHRAIN,
        self::BANGLADESH                                           => self::BANGLADESH,
        self::ARMENIA                                              => self::ARMENIA,
        self::BARBADOS                                             => self::BARBADOS,
        self::BELGIUM                                              => self::BELGIUM,
        self::BHUTAN                                               => self::BHUTAN,
        self::BOLIVIA                                              => self::BOLIVIA,
        self::BOSNIA_AND_HERZEGOVINA                               => self::BOSNIA_AND_HERZEGOVINA,
        self::BOTSWANA                                             => self::BOTSWANA,
        self::BRAZIL                                               => self::BRAZIL,
        self::BELIZE                                               => self::BELIZE,
        self::SOLOMON_ISLANDS                                      => self::SOLOMON_ISLANDS,
        self::BRUNEI_DARUSSALAM                                    => self::BRUNEI_DARUSSALAM,
        self::BULGARIA                                             => self::BULGARIA,
        self::MYANMAR                                              => self::MYANMAR,
        self::BURUNDI                                              => self::BURUNDI,
        self::BELARUS                                              => self::BELARUS,
        self::CAMBODIA                                             => self::CAMBODIA,
        self::CAMEROON                                             => self::CAMEROON,
        self::CANADA                                               => self::CANADA,
        self::CABO_VERDE                                           => self::CABO_VERDE,
        self::CENTRAL_AFRICAN_REPUBLIC                             => self::CENTRAL_AFRICAN_REPUBLIC,
        self::SRI_LANKA                                            => self::SRI_LANKA,
        self::CHAD                                                 => self::CHAD,
        self::CHILE                                                => self::CHILE,
        self::CHINA                                                => self::CHINA,
        self::COLOMBIA                                             => self::COLOMBIA,
        self::COMOROS                                              => self::COMOROS,
        self::CONGO                                                => self::CONGO,
        self::CONGO                                                => self::CONGO,
        self::COSTA_RICA                                           => self::COSTA_RICA,
        self::CROATIA                                              => self::CROATIA,
        self::CUBA                                                 => self::CUBA,
        self::CYPRUS                                               => self::CYPRUS,
        self::CZECHIA                                              => self::CZECHIA,
        self::BENIN                                                => self::BENIN,
        self::DENMARK                                              => self::DENMARK,
        self::DOMINICA                                             => self::DOMINICA,
        self::DOMINICAN_REPUBLIC                                   => self::DOMINICAN_REPUBLIC,
        self::ECUADOR                                              => self::ECUADOR,
        self::EL_SALVADOR                                          => self::EL_SALVADOR,
        self::EQUATORIAL_GUINEA                                    => self::EQUATORIAL_GUINEA,
        self::ETHIOPIA                                             => self::ETHIOPIA,
        self::ERITREA                                              => self::ERITREA,
        self::ESTONIA                                              => self::ESTONIA,
        self::FIJI                                                 => self::FIJI,
        self::FINLAND                                              => self::FINLAND,
        self::FRANCE                                               => self::FRANCE,
        self::DJIBOUTI                                             => self::DJIBOUTI,
        self::GABON                                                => self::GABON,
        self::GEORGIA                                              => self::GEORGIA,
        self::GAMBIA                                               => self::GAMBIA,
        self::GERMANY                                              => self::GERMANY,
        self::GHANA                                                => self::GHANA,
        self::KIRIBATI                                             => self::KIRIBATI,
        self::GREECE                                               => self::GREECE,
        self::GRENADA                                              => self::GRENADA,
        self::GUATEMALA                                            => self::GUATEMALA,
        self::GUINEA                                               => self::GUINEA,
        self::GUYANA                                               => self::GUYANA,
        self::HAITI                                                => self::HAITI,
        self::HOLY_SEE                                             => self::HOLY_SEE,
        self::HONDURAS                                             => self::HONDURAS,
        self::HUNGARY                                              => self::HUNGARY,
        self::ICELAND                                              => self::ICELAND,
        self::INDIA                                                => self::INDIA,
        self::INDONESIA                                            => self::INDONESIA,
        self::IRAN                                                 => self::IRAN,
        self::IRAQ                                                 => self::IRAQ,
        self::IRELAND                                              => self::IRELAND,
        self::ISRAEL                                               => self::ISRAEL,
        self::ITALY                                                => self::ITALY,
        self::COTE_D_IVOIRE                                        => self::COTE_D_IVOIRE,
        self::JAMAICA                                              => self::JAMAICA,
        self::JAPAN                                                => self::JAPAN,
        self::KAZAKHSTAN                                           => self::KAZAKHSTAN,
        self::JORDAN                                               => self::JORDAN,
        self::KENYA                                                => self::KENYA,
        self::KOREA_PEOPLES_DEMOCRATIC_REPUBLIC                    => self::KOREA_PEOPLES_DEMOCRATIC_REPUBLIC,
        self::KOREA_REPUBLIC                                       => self::KOREA_REPUBLIC,
        self::KUWAIT                                               => self::KUWAIT,
        self::KYRGYZSTAN                                           => self::KYRGYZSTAN,
        self::LAO_PEOPLES_DEMOCRATIC_REPUBLIC                      => self::LAO_PEOPLES_DEMOCRATIC_REPUBLIC,
        self::LEBANON                                              => self::LEBANON,
        self::LESOTHO                                              => self::LESOTHO,
        self::LATVIA                                               => self::LATVIA,
        self::LIBERIA                                              => self::LIBERIA,
        self::LIBYA                                                => self::LIBYA,
        self::LIECHTENSTEIN                                        => self::LIECHTENSTEIN,
        self::LITHUANIA                                            => self::LITHUANIA,
        self::LUXEMBOURG                                           => self::LUXEMBOURG,
        self::MADAGASCAR                                           => self::MADAGASCAR,
        self::MALAWI                                               => self::MALAWI,
        self::MALAYSIA                                             => self::MALAYSIA,
        self::MALDIVES                                             => self::MALDIVES,
        self::MALI                                                 => self::MALI,
        self::MALTA                                                => self::MALTA,
        self::MAURITANIA                                           => self::MAURITANIA,
        self::MAURITIUS                                            => self::MAURITIUS,
        self::MEXICO                                               => self::MEXICO,
        self::MONACO                                               => self::MONACO,
        self::MONGOLIA                                             => self::MONGOLIA,
        self::MOLDOVA                                              => self::MOLDOVA,
        self::MONTENEGRO                                           => self::MONTENEGRO,
        self::MOROCCO                                              => self::MOROCCO,
        self::MOZAMBIQUE                                           => self::MOZAMBIQUE,
        self::OMAN                                                 => self::OMAN,
        self::NAMIBIA                                              => self::NAMIBIA,
        self::NAURU                                                => self::NAURU,
        self::NEPAL                                                => self::NEPAL,
        self::NETHERLANDS                                          => self::NETHERLANDS,
        self::VANUATU                                              => self::VANUATU,
        self::NEW_ZEALAND                                          => self::NEW_ZEALAND,
        self::NICARAGUA                                            => self::NICARAGUA,
        self::NIGER                                                => self::NIGER,
        self::NIGERIA                                              => self::NIGERIA,
        self::NORWAY                                               => self::NORWAY,
        self::MICRONESIA                                           => self::MICRONESIA,
        self::MARSHALL_ISLANDS                                     => self::MARSHALL_ISLANDS,
        self::PALAU                                                => self::PALAU,
        self::PAKISTAN                                             => self::PAKISTAN,
        self::PANAMA                                               => self::PANAMA,
        self::PAPUA_NEW_GUINEA                                     => self::PAPUA_NEW_GUINEA,
        self::PARAGUAY                                             => self::PARAGUAY,
        self::PERU                                                 => self::PERU,
        self::PHILIPPINES                                          => self::PHILIPPINES,
        self::POLAND                                               => self::POLAND,
        self::PORTUGAL                                             => self::PORTUGAL,
        self::GUINEA_BISSAU                                        => self::GUINEA_BISSAU,
        self::TIMOR_LESTE                                          => self::TIMOR_LESTE,
        self::QATAR                                                => self::QATAR,
        self::ROMANIA                                              => self::ROMANIA,
        self::RUSSIAN_FEDERATION                                   => self::RUSSIAN_FEDERATION,
        self::RWANDA                                               => self::RWANDA,
        self::SAINT_KITTS_AND_NEVIS                                => self::SAINT_KITTS_AND_NEVIS,
        self::SAINT_LUCIA                                          => self::SAINT_LUCIA,
        self::SAINT_VINCENT_AND_THE_GRENADINES                     => self::SAINT_VINCENT_AND_THE_GRENADINES,
        self::SAN_MARINO                                           => self::SAN_MARINO,
        self::SAO_TOME_AND_PRINCIPE                                => self::SAO_TOME_AND_PRINCIPE,
        self::SAUDI_ARABIA                                         => self::SAUDI_ARABIA,
        self::SENEGAL                                              => self::SENEGAL,
        self::SERBIA                                               => self::SERBIA,
        self::SEYCHELLES                                           => self::SEYCHELLES,
        self::SIERRA_LEONE                                         => self::SIERRA_LEONE,
        self::SINGAPORE                                            => self::SINGAPORE,
        self::SLOVAKIA                                             => self::SLOVAKIA,
        self::VIET_NAM                                             => self::VIET_NAM,
        self::SLOVENIA                                             => self::SLOVENIA,
        self::SOMALIA                                              => self::SOMALIA,
        self::SOUTH_AFRICA                                         => self::SOUTH_AFRICA,
        self::ZIMBABWE                                             => self::ZIMBABWE,
        self::SPAIN                                                => self::SPAIN,
        self::SOUTH_SUDAN                                          => self::SOUTH_SUDAN,
        self::SUDAN                                                => self::SUDAN,
        self::SURINAME                                             => self::SURINAME,
        self::SWAZILAND                                            => self::SWAZILAND,
        self::SWEDEN                                               => self::SWEDEN,
        self::SWITZERLAND                                          => self::SWITZERLAND,
        self::SYRIAN_ARAB_REPUBLIC                                 => self::SYRIAN_ARAB_REPUBLIC,
        self::TAJIKISTAN                                           => self::TAJIKISTAN,
        self::THAILAND                                             => self::THAILAND,
        self::TOGO                                                 => self::TOGO,
        self::TONGA                                                => self::TONGA,
        self::TRINIDAD_AND_TOBAGO                                  => self::TRINIDAD_AND_TOBAGO,
        self::UNITED_ARAB_EMIRATES                                 => self::UNITED_ARAB_EMIRATES,
        self::TUNISIA                                              => self::TUNISIA,
        self::TURKEY                                               => self::TURKEY,
        self::TURKMENISTAN                                         => self::TURKMENISTAN,
        self::TUVALU                                               => self::TUVALU,
        self::UGANDA                                               => self::UGANDA,
        self::UKRAINE                                              => self::UKRAINE,
        self::MACEDONIA                                            => self::MACEDONIA,
        self::EGYPT                                                => self::EGYPT,
        self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND => self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND,
        self::TANZANIA                                             => self::TANZANIA,
        self::UNITED_STATES_OF_AMERICA                             => self::UNITED_STATES_OF_AMERICA,
        self::BURKINA_FASO                                         => self::BURKINA_FASO,
        self::URUGUAY                                              => self::URUGUAY,
        self::UZBEKISTAN                                           => self::UZBEKISTAN,
        self::VENEZUELA                                            => self::VENEZUELA,
        self::SAMOA                                                => self::SAMOA,
        self::YEMEN                                                => self::YEMEN,
        self::ZAMBIA                                               => self::ZAMBIA,
    ];
    public static $dependentNum = [
        self::ANTARCTICA                                   => self::ANTARCTICA,
        self::AMERICAN_SAMOA                               => self::AMERICAN_SAMOA,
        self::BERMUDA                                      => self::BERMUDA,
        self::BOUVET_ISLAND                                => self::BOUVET_ISLAND,
        self::BRITISH_INDIAN_OCEAN_TERRITORY               => self::BRITISH_INDIAN_OCEAN_TERRITORY,
        self::BRITISH_VIRGIN_ISLANDS                       => self::BRITISH_VIRGIN_ISLANDS,
        self::CAYMAN_ISLANDS                               => self::CAYMAN_ISLANDS,
        self::TAIWAN                                       => self::TAIWAN,
        self::CHRISTMAS_ISLAND                             => self::CHRISTMAS_ISLAND,
        self::COCOS_ISLANDS                                => self::COCOS_ISLANDS,
        self::MAYOTTE                                      => self::MAYOTTE,
        self::COOK_ISLANDS                                 => self::COOK_ISLANDS,
        self::FAROE_ISLANDS                                => self::FAROE_ISLANDS,
        self::FALKLAND_ISLANDS                             => self::FALKLAND_ISLANDS,
        self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,
        self::ALAND_ISLANDS                                => self::ALAND_ISLANDS,
        self::FRENCH_GUIANA                                => self::FRENCH_GUIANA,
        self::FRENCH_POLYNESIA                             => self::FRENCH_POLYNESIA,
        self::FRENCH_SOUTHERN_TERRITORIES                  => self::FRENCH_SOUTHERN_TERRITORIES,
        self::PALESTINE_STATE_OF                           => self::PALESTINE_STATE_OF,
        self::GIBRALTAR                                    => self::GIBRALTAR,
        self::GREENLAND                                    => self::GREENLAND,
        self::GUADELOUPE                                   => self::GUADELOUPE,
        self::GUAM                                         => self::GUAM,
        self::HEARD_ISLAND_AND_MC_DONALD_ISLANDS           => self::HEARD_ISLAND_AND_MC_DONALD_ISLANDS,
        self::HONG_KONG                                    => self::HONG_KONG,
        self::MACAO                                        => self::MACAO,
        self::MARTINIQUE                                   => self::MARTINIQUE,
        self::MONTSERRAT                                   => self::MONTSERRAT,
        self::CURACAO                                      => self::CURACAO,
        self::ARUBA                                        => self::ARUBA,
        self::DUTCH_SINT_MAARTEN                           => self::DUTCH_SINT_MAARTEN,
        self::BONAIRE_SINT_EUSTATIUS_AND_SABA              => self::BONAIRE_SINT_EUSTATIUS_AND_SABA,
        self::NEW_CALEDONIA                                => self::NEW_CALEDONIA,
        self::NIUE                                         => self::NIUE,
        self::NORFOLK_ISLAND                               => self::NORFOLK_ISLAND,
        self::NORTHERN_MARIANA_ISLANDS                     => self::NORTHERN_MARIANA_ISLANDS,
        self::UNITED_STATES_MINOR_OUTLYING_ISLANDS         => self::UNITED_STATES_MINOR_OUTLYING_ISLANDS,
        self::PITCAIRN                                     => self::PITCAIRN,
        self::PUERTO_RICO                                  => self::PUERTO_RICO,
        self::REUNION                                      => self::REUNION,
        self::SAINT_BARTHELEMY                             => self::SAINT_BARTHELEMY,
        self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA  => self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA,
        self::ANGUILLA                                     => self::ANGUILLA,
        self::FRENCH_SAINT_MARTIN                          => self::FRENCH_SAINT_MARTIN,
        self::SAINT_PIERRE_AND_MIQUELON                    => self::SAINT_PIERRE_AND_MIQUELON,
        self::WESTERN_SAHARA                               => self::WESTERN_SAHARA,
        self::SVALBARD_AND_JAN_MAYEN                       => self::SVALBARD_AND_JAN_MAYEN,
        self::TOKELAU                                      => self::TOKELAU,
        self::TURKS_AND_CAICOS_ISLANDS                     => self::TURKS_AND_CAICOS_ISLANDS,
        self::GUERNSEY                                     => self::GUERNSEY,
        self::JERSEY                                       => self::JERSEY,
        self::ISLE_OF_MAN                                  => self::ISLE_OF_MAN,
        self::US_VIRGIN_ISLANDS                            => self::US_VIRGIN_ISLANDS,
        self::WALLIS_AND_FUTUNA                            => self::WALLIS_AND_FUTUNA,
    ];
    public static $independentAlpha2 = [
        self::ABKHAZIA                                             => 'AB',
        self::AFGHANISTAN                                          => 'AF',
        self::ALBANIA                                              => 'AL',
        self::ALGERIA                                              => 'DZ',
        self::ANDORRA                                              => 'AD',
        self::ANGOLA                                               => 'AO',
        self::ANTIGUA_AND_BARBUDA                                  => 'AG',
        self::AZERBAIJAN                                           => 'AZ',
        self::ARGENTINA                                            => 'AR',
        self::AUSTRALIA                                            => 'AU',
        self::AUSTRIA                                              => 'AT',
        self::BAHAMAS                                              => 'BS',
        self::BAHRAIN                                              => 'BH',
        self::BANGLADESH                                           => 'BD',
        self::ARMENIA                                              => 'AM',
        self::BARBADOS                                             => 'BB',
        self::BELGIUM                                              => 'BE',
        self::BHUTAN                                               => 'BT',
        self::BOLIVIA                                              => 'BO',
        self::BOSNIA_AND_HERZEGOVINA                               => 'BA',
        self::BOTSWANA                                             => 'BW',
        self::BRAZIL                                               => 'BR',
        self::BELIZE                                               => 'BZ',
        self::SOLOMON_ISLANDS                                      => 'SB',
        self::BRUNEI_DARUSSALAM                                    => 'BN',
        self::BULGARIA                                             => 'BG',
        self::MYANMAR                                              => 'MM',
        self::BURUNDI                                              => 'BI',
        self::BELARUS                                              => 'BY',
        self::CAMBODIA                                             => 'KH',
        self::CAMEROON                                             => 'CM',
        self::CANADA                                               => 'CA',
        self::CABO_VERDE                                           => 'CV',
        self::CENTRAL_AFRICAN_REPUBLIC                             => 'CF',
        self::SRI_LANKA                                            => 'LK',
        self::CHAD                                                 => 'TD',
        self::CHILE                                                => 'CL',
        self::CHINA                                                => 'CN',
        self::COLOMBIA                                             => 'CO',
        self::COMOROS                                              => 'KM',
        self::CONGO                                                => 'CG',
        self::CONGO_DEMOCRATIC_REPUBLIC                            => 'CD',
        self::COSTA_RICA                                           => 'CR',
        self::CROATIA                                              => 'HR',
        self::CUBA                                                 => 'CU',
        self::CYPRUS                                               => 'CY',
        self::CZECHIA                                              => 'CZ',
        self::BENIN                                                => 'BJ',
        self::DENMARK                                              => 'DK',
        self::DOMINICA                                             => 'DM',
        self::DOMINICAN_REPUBLIC                                   => 'DO',
        self::ECUADOR                                              => 'EC',
        self::EL_SALVADOR                                          => 'SV',
        self::EQUATORIAL_GUINEA                                    => 'GQ',
        self::ETHIOPIA                                             => 'ET',
        self::ERITREA                                              => 'ER',
        self::ESTONIA                                              => 'EE',
        self::FIJI                                                 => 'FJ',
        self::FINLAND                                              => 'FI',
        self::FRANCE                                               => 'FR',
        self::DJIBOUTI                                             => 'DJ',
        self::GABON                                                => 'GA',
        self::GEORGIA                                              => 'GE',
        self::GAMBIA                                               => 'GM',
        self::GERMANY                                              => 'DE',
        self::GHANA                                                => 'GH',
        self::KIRIBATI                                             => 'KI',
        self::GREECE                                               => 'GR',
        self::GRENADA                                              => 'GD',
        self::GUATEMALA                                            => 'GT',
        self::GUINEA                                               => 'GN',
        self::GUYANA                                               => 'GY',
        self::HAITI                                                => 'HT',
        self::HOLY_SEE                                             => 'VA',
        self::HONDURAS                                             => 'HN',
        self::HUNGARY                                              => 'HU',
        self::ICELAND                                              => 'IS',
        self::INDIA                                                => 'IN',
        self::INDONESIA                                            => 'ID',
        self::IRAN                                                 => 'IR',
        self::IRAQ                                                 => 'IQ',
        self::IRELAND                                              => 'IE',
        self::ISRAEL                                               => 'IL',
        self::ITALY                                                => 'IT',
        self::COTE_D_IVOIRE                                        => 'CI',
        self::JAMAICA                                              => 'JM',
        self::JAPAN                                                => 'JP',
        self::KAZAKHSTAN                                           => 'KZ',
        self::JORDAN                                               => 'JO',
        self::KENYA                                                => 'KE',
        self::KOREA_PEOPLES_DEMOCRATIC_REPUBLIC                    => 'KP',
        self::KOREA_REPUBLIC                                       => 'KR',
        self::KUWAIT                                               => 'KW',
        self::KYRGYZSTAN                                           => 'KG',
        self::LAO_PEOPLES_DEMOCRATIC_REPUBLIC                      => 'LA',
        self::LEBANON                                              => 'LB',
        self::LESOTHO                                              => 'LS',
        self::LATVIA                                               => 'LV',
        self::LIBERIA                                              => 'LR',
        self::LIBYA                                                => 'LY',
        self::LIECHTENSTEIN                                        => 'LI',
        self::LITHUANIA                                            => 'LT',
        self::LUXEMBOURG                                           => 'LU',
        self::MADAGASCAR                                           => 'MG',
        self::MALAWI                                               => 'MW',
        self::MALAYSIA                                             => 'MY',
        self::MALDIVES                                             => 'MV',
        self::MALI                                                 => 'ML',
        self::MALTA                                                => 'MT',
        self::MAURITANIA                                           => 'MR',
        self::MAURITIUS                                            => 'MU',
        self::MEXICO                                               => 'MX',
        self::MONACO                                               => 'MC',
        self::MONGOLIA                                             => 'MN',
        self::MOLDOVA                                              => 'MD',
        self::MONTENEGRO                                           => 'ME',
        self::MOROCCO                                              => 'MA',
        self::MOZAMBIQUE                                           => 'MZ',
        self::OMAN                                                 => 'OM',
        self::NAMIBIA                                              => 'NA',
        self::NAURU                                                => 'NR',
        self::NEPAL                                                => 'NP',
        self::NETHERLANDS                                          => 'NL',
        self::VANUATU                                              => 'VU',
        self::NEW_ZEALAND                                          => 'NZ',
        self::NICARAGUA                                            => 'NI',
        self::NIGER                                                => 'NE',
        self::NIGERIA                                              => 'NG',
        self::NORWAY                                               => 'NO',
        self::MICRONESIA                                           => 'FM',
        self::MARSHALL_ISLANDS                                     => 'MH',
        self::PALAU                                                => 'PW',
        self::PAKISTAN                                             => 'PK',
        self::PANAMA                                               => 'PA',
        self::PAPUA_NEW_GUINEA                                     => 'PG',
        self::PARAGUAY                                             => 'PY',
        self::PERU                                                 => 'PE',
        self::PHILIPPINES                                          => 'PH',
        self::POLAND                                               => 'PL',
        self::PORTUGAL                                             => 'PT',
        self::GUINEA_BISSAU                                        => 'GW',
        self::TIMOR_LESTE                                          => 'TL',
        self::QATAR                                                => 'QA',
        self::ROMANIA                                              => 'RO',
        self::RUSSIAN_FEDERATION                                   => 'RU',
        self::RWANDA                                               => 'RW',
        self::SAINT_KITTS_AND_NEVIS                                => 'KN',
        self::SAINT_LUCIA                                          => 'LC',
        self::SAINT_VINCENT_AND_THE_GRENADINES                     => 'VC',
        self::SAN_MARINO                                           => 'SM',
        self::SAO_TOME_AND_PRINCIPE                                => 'ST',
        self::SAUDI_ARABIA                                         => 'SA',
        self::SENEGAL                                              => 'SN',
        self::SERBIA                                               => 'RS',
        self::SEYCHELLES                                           => 'SC',
        self::SIERRA_LEONE                                         => 'SL',
        self::SINGAPORE                                            => 'SG',
        self::SLOVAKIA                                             => 'SK',
        self::VIET_NAM                                             => 'VN',
        self::SLOVENIA                                             => 'SI',
        self::SOMALIA                                              => 'SO',
        self::SOUTH_AFRICA                                         => 'ZA',
        self::ZIMBABWE                                             => 'ZW',
        self::SPAIN                                                => 'ES',
        self::SOUTH_SUDAN                                          => 'SS',
        self::SUDAN                                                => 'SD',
        self::SURINAME                                             => 'SR',
        self::SWAZILAND                                            => 'SZ',
        self::SWEDEN                                               => 'SE',
        self::SWITZERLAND                                          => 'CH',
        self::SYRIAN_ARAB_REPUBLIC                                 => 'SY',
        self::TAJIKISTAN                                           => 'TJ',
        self::THAILAND                                             => 'TH',
        self::TOGO                                                 => 'TG',
        self::TONGA                                                => 'TO',
        self::TRINIDAD_AND_TOBAGO                                  => 'TT',
        self::UNITED_ARAB_EMIRATES                                 => 'AE',
        self::TUNISIA                                              => 'TN',
        self::TURKEY                                               => 'TR',
        self::TURKMENISTAN                                         => 'TM',
        self::TUVALU                                               => 'TV',
        self::UGANDA                                               => 'UG',
        self::UKRAINE                                              => 'UA',
        self::MACEDONIA                                            => 'MK',
        self::EGYPT                                                => 'EG',
        self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND => 'GB',
        self::TANZANIA                                             => 'TZ',
        self::UNITED_STATES_OF_AMERICA                             => 'US',
        self::BURKINA_FASO                                         => 'BF',
        self::URUGUAY                                              => 'UY',
        self::UZBEKISTAN                                           => 'UZ',
        self::VENEZUELA                                            => 'VE',
        self::SAMOA                                                => 'WS',
        self::YEMEN                                                => 'YE',
        self::ZAMBIA                                               => 'ZM',
    ];
    public static $independentAlpha3 = [
        self::ABKHAZIA                                             => 'ABH',
        self::AFGHANISTAN                                          => 'AFG',
        self::ALBANIA                                              => 'ALB',
        self::ALGERIA                                              => 'DZA',
        self::ANDORRA                                              => 'AND',
        self::ANGOLA                                               => 'AGO',
        self::ANTIGUA_AND_BARBUDA                                  => 'ATG',
        self::AZERBAIJAN                                           => 'AZE',
        self::ARGENTINA                                            => 'ARG',
        self::AUSTRALIA                                            => 'AUS',
        self::AUSTRIA                                              => 'AUT',
        self::BAHAMAS                                              => 'BHS',
        self::BAHRAIN                                              => 'BHR',
        self::BANGLADESH                                           => 'BGD',
        self::ARMENIA                                              => 'ARM',
        self::BARBADOS                                             => 'BRB',
        self::BELGIUM                                              => 'BEL',
        self::BHUTAN                                               => 'BTN',
        self::BOLIVIA                                              => 'BOL',
        self::BOSNIA_AND_HERZEGOVINA                               => 'BIH',
        self::BOTSWANA                                             => 'BWA',
        self::BRAZIL                                               => 'BRA',
        self::BELIZE                                               => 'BLZ',
        self::SOLOMON_ISLANDS                                      => 'SLB',
        self::BRUNEI_DARUSSALAM                                    => 'BRN',
        self::BULGARIA                                             => 'BGR',
        self::MYANMAR                                              => 'MMR',
        self::BURUNDI                                              => 'BDI',
        self::BELARUS                                              => 'BLR',
        self::CAMBODIA                                             => 'KHM',
        self::CAMEROON                                             => 'CMR',
        self::CANADA                                               => 'CAN',
        self::CABO_VERDE                                           => 'CPV',
        self::CENTRAL_AFRICAN_REPUBLIC                             => 'CAF',
        self::SRI_LANKA                                            => 'LKA',
        self::CHAD                                                 => 'TCD',
        self::CHILE                                                => 'CHL',
        self::CHINA                                                => 'CHN',
        self::COLOMBIA                                             => 'COL',
        self::COMOROS                                              => 'COM',
        self::CONGO                                                => 'COG',
        self::CONGO_DEMOCRATIC_REPUBLIC                            => 'COD',
        self::COSTA_RICA                                           => 'CRI',
        self::CROATIA                                              => 'HRV',
        self::CUBA                                                 => 'CUB',
        self::CYPRUS                                               => 'CYP',
        self::CZECHIA                                              => 'CZE',
        self::BENIN                                                => 'BEN',
        self::DENMARK                                              => 'DNK',
        self::DOMINICA                                             => 'DMA',
        self::DOMINICAN_REPUBLIC                                   => 'DOM',
        self::ECUADOR                                              => 'ECU',
        self::EL_SALVADOR                                          => 'SLV',
        self::EQUATORIAL_GUINEA                                    => 'GNQ',
        self::ETHIOPIA                                             => 'ETH',
        self::ERITREA                                              => 'ERI',
        self::ESTONIA                                              => 'EST',
        self::FIJI                                                 => 'FJI',
        self::FINLAND                                              => 'FIN',
        self::FRANCE                                               => 'FRA',
        self::DJIBOUTI                                             => 'DJI',
        self::GABON                                                => 'GAB',
        self::GEORGIA                                              => 'GEO',
        self::GAMBIA                                               => 'GMB',
        self::GERMANY                                              => 'DEU',
        self::GHANA                                                => 'GHA',
        self::KIRIBATI                                             => 'KIR',
        self::GREECE                                               => 'GRC',
        self::GRENADA                                              => 'GRD',
        self::GUATEMALA                                            => 'GTM',
        self::GUINEA                                               => 'GIN',
        self::GUYANA                                               => 'GUY',
        self::HAITI                                                => 'HTI',
        self::HOLY_SEE                                             => 'VAT',
        self::HONDURAS                                             => 'HND',
        self::HUNGARY                                              => 'HUN',
        self::ICELAND                                              => 'ISL',
        self::INDIA                                                => 'IND',
        self::INDONESIA                                            => 'IDN',
        self::IRAN                                                 => 'IRN',
        self::IRAQ                                                 => 'IRQ',
        self::IRELAND                                              => 'IRL',
        self::ISRAEL                                               => 'ISR',
        self::ITALY                                                => 'ITA',
        self::COTE_D_IVOIRE                                        => 'CIV',
        self::JAMAICA                                              => 'JAM',
        self::JAPAN                                                => 'JPN',
        self::KAZAKHSTAN                                           => 'KAZ',
        self::JORDAN                                               => 'JOR',
        self::KENYA                                                => 'KEN',
        self::KOREA_PEOPLES_DEMOCRATIC_REPUBLIC                    => 'PRK',
        self::KOREA_REPUBLIC                                       => 'KOR',
        self::KUWAIT                                               => 'KWT',
        self::KYRGYZSTAN                                           => 'KGZ',
        self::LAO_PEOPLES_DEMOCRATIC_REPUBLIC                      => 'LAO',
        self::LEBANON                                              => 'LBN',
        self::LESOTHO                                              => 'LSO',
        self::LATVIA                                               => 'LVA',
        self::LIBERIA                                              => 'LBR',
        self::LIBYA                                                => 'LBY',
        self::LIECHTENSTEIN                                        => 'LIE',
        self::LITHUANIA                                            => 'LTU',
        self::LUXEMBOURG                                           => 'LUX',
        self::MADAGASCAR                                           => 'MDG',
        self::MALAWI                                               => 'MWI',
        self::MALAYSIA                                             => 'MYS',
        self::MALDIVES                                             => 'MDV',
        self::MALI                                                 => 'MLI',
        self::MALTA                                                => 'MLT',
        self::MAURITANIA                                           => 'MRT',
        self::MAURITIUS                                            => 'MUS',
        self::MEXICO                                               => 'MEX',
        self::MONACO                                               => 'MCO',
        self::MONGOLIA                                             => 'MNG',
        self::MOLDOVA                                              => 'MDA',
        self::MONTENEGRO                                           => 'MNE',
        self::MOROCCO                                              => 'MAR',
        self::MOZAMBIQUE                                           => 'MOZ',
        self::OMAN                                                 => 'OMN',
        self::NAMIBIA                                              => 'NAM',
        self::NAURU                                                => 'NRU',
        self::NEPAL                                                => 'NPL',
        self::NETHERLANDS                                          => 'NLD',
        self::VANUATU                                              => 'VUT',
        self::NEW_ZEALAND                                          => 'NZL',
        self::NICARAGUA                                            => 'NIC',
        self::NIGER                                                => 'NER',
        self::NIGERIA                                              => 'NGA',
        self::NORWAY                                               => 'NOR',
        self::MICRONESIA                                           => 'FSM',
        self::MARSHALL_ISLANDS                                     => 'MHL',
        self::PALAU                                                => 'PLW',
        self::PAKISTAN                                             => 'PAK',
        self::PANAMA                                               => 'PAN',
        self::PAPUA_NEW_GUINEA                                     => 'PNG',
        self::PARAGUAY                                             => 'PRY',
        self::PERU                                                 => 'PER',
        self::PHILIPPINES                                          => 'PHL',
        self::POLAND                                               => 'POL',
        self::PORTUGAL                                             => 'PRT',
        self::GUINEA_BISSAU                                        => 'GNB',
        self::TIMOR_LESTE                                          => 'TLS',
        self::QATAR                                                => 'QAT',
        self::ROMANIA                                              => 'ROU',
        self::RUSSIAN_FEDERATION                                   => 'RUS',
        self::RWANDA                                               => 'RWA',
        self::SAINT_KITTS_AND_NEVIS                                => 'KNA',
        self::SAINT_LUCIA                                          => 'LCA',
        self::SAINT_VINCENT_AND_THE_GRENADINES                     => 'VCT',
        self::SAN_MARINO                                           => 'SMR',
        self::SAO_TOME_AND_PRINCIPE                                => 'STP',
        self::SAUDI_ARABIA                                         => 'SAU',
        self::SENEGAL                                              => 'SEN',
        self::SERBIA                                               => 'SRB',
        self::SEYCHELLES                                           => 'SYC',
        self::SIERRA_LEONE                                         => 'SLE',
        self::SINGAPORE                                            => 'SGP',
        self::SLOVAKIA                                             => 'SVK',
        self::VIET_NAM                                             => 'VNM',
        self::SLOVENIA                                             => 'SVN',
        self::SOMALIA                                              => 'SOM',
        self::SOUTH_AFRICA                                         => 'ZAF',
        self::ZIMBABWE                                             => 'ZWE',
        self::SPAIN                                                => 'ESP',
        self::SOUTH_SUDAN                                          => 'SSD',
        self::SUDAN                                                => 'SDN',
        self::SURINAME                                             => 'SUR',
        self::SWAZILAND                                            => 'SWZ',
        self::SWEDEN                                               => 'SWE',
        self::SWITZERLAND                                          => 'CHE',
        self::SYRIAN_ARAB_REPUBLIC                                 => 'SYR',
        self::TAJIKISTAN                                           => 'TJK',
        self::THAILAND                                             => 'THA',
        self::TOGO                                                 => 'TGO',
        self::TONGA                                                => 'TON',
        self::TRINIDAD_AND_TOBAGO                                  => 'TTO',
        self::UNITED_ARAB_EMIRATES                                 => 'ARE',
        self::TUNISIA                                              => 'TUN',
        self::TURKEY                                               => 'TUR',
        self::TURKMENISTAN                                         => 'TKM',
        self::TUVALU                                               => 'TUV',
        self::UGANDA                                               => 'UGA',
        self::UKRAINE                                              => 'UKR',
        self::MACEDONIA                                            => 'MKD',
        self::EGYPT                                                => 'EGY',
        self::UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND => 'GBR',
        self::TANZANIA                                             => 'TZA',
        self::UNITED_STATES_OF_AMERICA                             => 'USA',
        self::BURKINA_FASO                                         => 'BFA',
        self::URUGUAY                                              => 'URY',
        self::UZBEKISTAN                                           => 'UZB',
        self::VENEZUELA                                            => 'VEN',
        self::SAMOA                                                => 'WSM',
        self::YEMEN                                                => 'YEM',
        self::ZAMBIA                                               => 'ZMB',
    ];
    public static $dependentAlpha2 = [
        self::ANTARCTICA                                   => 'AQ',
        self::AMERICAN_SAMOA                               => 'AS',
        self::BERMUDA                                      => 'BM',
        self::BOUVET_ISLAND                                => 'BV',
        self::BRITISH_INDIAN_OCEAN_TERRITORY               => 'IO',
        self::BRITISH_VIRGIN_ISLANDS                       => 'VG',
        self::CAYMAN_ISLANDS                               => 'KY',
        self::TAIWAN                                       => 'TW',
        self::CHRISTMAS_ISLAND                             => 'CX',
        self::COCOS_ISLANDS                                => 'CC',
        self::MAYOTTE                                      => 'YT',
        self::COOK_ISLANDS                                 => 'CK',
        self::FAROE_ISLANDS                                => 'FO',
        self::FALKLAND_ISLANDS                             => 'FK',
        self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => 'GS',
        self::ALAND_ISLANDS                                => 'AX',
        self::FRENCH_GUIANA                                => 'GF',
        self::FRENCH_POLYNESIA                             => 'PF',
        self::FRENCH_SOUTHERN_TERRITORIES                  => 'TF',
        self::PALESTINE_STATE_OF                           => 'PS',
        self::GIBRALTAR                                    => 'GI',
        self::GREENLAND                                    => 'GL',
        self::GUADELOUPE                                   => 'GP',
        self::GUAM                                         => 'GU',
        self::HEARD_ISLAND_AND_MC_DONALD_ISLANDS           => 'HM',
        self::HONG_KONG                                    => 'HK',
        self::MACAO                                        => 'MO',
        self::MARTINIQUE                                   => 'MQ',
        self::MONTSERRAT                                   => 'MS',
        self::CURACAO                                      => 'CW',
        self::ARUBA                                        => 'AW',
        self::DUTCH_SINT_MAARTEN                           => 'SX',
        self::BONAIRE_SINT_EUSTATIUS_AND_SABA              => 'BQ',
        self::NEW_CALEDONIA                                => 'NC',
        self::NIUE                                         => 'NU',
        self::NORFOLK_ISLAND                               => 'NF',
        self::NORTHERN_MARIANA_ISLANDS                     => 'MP',
        self::UNITED_STATES_MINOR_OUTLYING_ISLANDS         => 'UM',
        self::PITCAIRN                                     => 'PN',
        self::PUERTO_RICO                                  => 'PR',
        self::REUNION                                      => 'RE',
        self::SAINT_BARTHELEMY                             => 'BL',
        self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA  => 'SH',
        self::ANGUILLA                                     => 'AI',
        self::FRENCH_SAINT_MARTIN                          => 'MF',
        self::SAINT_PIERRE_AND_MIQUELON                    => 'PM',
        self::WESTERN_SAHARA                               => 'EH',
        self::SVALBARD_AND_JAN_MAYEN                       => 'SJ',
        self::TOKELAU                                      => 'TK',
        self::TURKS_AND_CAICOS_ISLANDS                     => 'TC',
        self::GUERNSEY                                     => 'GG',
        self::JERSEY                                       => 'JE',
        self::ISLE_OF_MAN                                  => 'IM',
        self::US_VIRGIN_ISLANDS                            => 'VI',
        self::WALLIS_AND_FUTUNA                            => 'WF',
    ];
    public static $dependentAlpha3 = [
        self::ANTARCTICA                                   => 'ATA',
        self::AMERICAN_SAMOA                               => 'ASM',
        self::BERMUDA                                      => 'BMU',
        self::BOUVET_ISLAND                                => 'BVT',
        self::BRITISH_INDIAN_OCEAN_TERRITORY               => 'IOT',
        self::BRITISH_VIRGIN_ISLANDS                       => 'VGB',
        self::CAYMAN_ISLANDS                               => 'CYM',
        self::TAIWAN                                       => 'TWN',
        self::CHRISTMAS_ISLAND                             => 'CXR',
        self::COCOS_ISLANDS                                => 'CCK',
        self::MAYOTTE                                      => 'MYT',
        self::COOK_ISLANDS                                 => 'COK',
        self::FAROE_ISLANDS                                => 'FRO',
        self::FALKLAND_ISLANDS                             => 'FLK',
        self::SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS => 'SGS',
        self::ALAND_ISLANDS                                => 'ALA',
        self::FRENCH_GUIANA                                => 'GUF',
        self::FRENCH_POLYNESIA                             => 'PYF',
        self::FRENCH_SOUTHERN_TERRITORIES                  => 'ATF',
        self::PALESTINE_STATE_OF                           => 'PSE',
        self::GIBRALTAR                                    => 'GIB',
        self::GREENLAND                                    => 'GRL',
        self::GUADELOUPE                                   => 'GLP',
        self::GUAM                                         => 'GUM',
        self::HEARD_ISLAND_AND_MC_DONALD_ISLANDS           => 'HMD',
        self::HONG_KONG                                    => 'HKG',
        self::MACAO                                        => 'MAC',
        self::MARTINIQUE                                   => 'MTQ',
        self::MONTSERRAT                                   => 'MSR',
        self::CURACAO                                      => 'CUW',
        self::ARUBA                                        => 'ABW',
        self::DUTCH_SINT_MAARTEN                           => 'SXM',
        self::BONAIRE_SINT_EUSTATIUS_AND_SABA              => 'BES',
        self::NEW_CALEDONIA                                => 'NCL',
        self::NIUE                                         => 'NIU',
        self::NORFOLK_ISLAND                               => 'NFK',
        self::NORTHERN_MARIANA_ISLANDS                     => 'MNP',
        self::UNITED_STATES_MINOR_OUTLYING_ISLANDS         => 'UMI',
        self::PITCAIRN                                     => 'PCN',
        self::PUERTO_RICO                                  => 'PRI',
        self::REUNION                                      => 'REU',
        self::SAINT_BARTHELEMY                             => 'BLM',
        self::SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA  => 'SHN',
        self::ANGUILLA                                     => 'AIA',
        self::FRENCH_SAINT_MARTIN                          => 'MAF',
        self::SAINT_PIERRE_AND_MIQUELON                    => 'SPM',
        self::WESTERN_SAHARA                               => 'ESH',
        self::SVALBARD_AND_JAN_MAYEN                       => 'SJM',
        self::TOKELAU                                      => 'TKL',
        self::TURKS_AND_CAICOS_ISLANDS                     => 'TCA',
        self::GUERNSEY                                     => 'GGY',
        self::JERSEY                                       => 'JEY',
        self::ISLE_OF_MAN                                  => 'IMN',
        self::US_VIRGIN_ISLANDS                            => 'VIR',
        self::WALLIS_AND_FUTUNA                            => 'WLF',
    ];
    public static $georgiaRegions = [
        self::GEORGIA_ABKHAZIA,
        self::GEORGIA_AJARIA,
        self::GEORGIA_TBILISI,
        self::GEORGIA_GURIA,
        self::GEORGIA_IMERETI,
        self::GEORGIA_K_AKHETI,
        self::GEORGIA_KVEMO_KARTLI,
        self::GEORGIA_MTSKHETA_MTIANETI,
        self::GEORGIA_RACH_A_LECHKHUMI_KVEMO_SVANETI,
        self::GEORGIA_SAMEGRELO_ZEMO_SVANETI,
        self::GEORGIA_SAMTSKHE_JAVAKHETI,
        self::GEORGIA_SHIDA_KARTLI,
    ];
    public static $russianFederationRegions = [
        self::RUSSIAN_FEDERATION_RESPUBLIKA_ADYGEYA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_ALTAY,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_BASHKORTOSTAN,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_BURYATIYA,
        self::RUSSIAN_FEDERATION_CHECHENSKAYA_RESPUBLIKA,
        self::RUSSIAN_FEDERATION_CHUVASHSKAYA_RESPUBLIKA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_DAGESTAN,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_INGUSHETIYA,
        self::RUSSIAN_FEDERATION_KABARDINO_BALKARSKAYA_RESPUBLIKA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_KALMYKIYA,
        self::RUSSIAN_FEDERATION_KARACHAYEVO_CHERKESSKAYA_RESPUBLIKA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_KARELIYA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_KHAKASIYA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_KOMI,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_MARIY_EL,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_MORDOVIYA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_SAKHA_YAKUTIYA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_SEVERNAYA_OSETIYA_ALANIYA,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_TATARSTAN,
        self::RUSSIAN_FEDERATION_RESPUBLIKA_TYVA_,
        self::RUSSIAN_FEDERATION_UDMURTSKAYA_RESPUBLIKA,
        self::RUSSIAN_FEDERATION_ALTAYSKIY_KRAY,
        self::RUSSIAN_FEDERATION_KAMCHATSKIY_KRAY,
        self::RUSSIAN_FEDERATION_KHABAROVSKIY_KRAY,
        self::RUSSIAN_FEDERATION_KRASNODARSKIY_KRAY,
        self::RUSSIAN_FEDERATION_KRASNOYARSKIY_KRAY,
        self::RUSSIAN_FEDERATION_PERMSKIY_KRAY,
        self::RUSSIAN_FEDERATION_PRIMORSKIY_KRAY,
        self::RUSSIAN_FEDERATION_STAVROPOLSKIY_KRAY,
        self::RUSSIAN_FEDERATION_ZABAYKALSKIY_KRAY,
        self::RUSSIAN_FEDERATION_AMURSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_ARKHANGELSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_ASTRAKHANSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_BELGORODSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_BRYANSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_CHELYABINSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_IRKUTSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_IVANOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KALININGRADSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KALUZHSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KEMEROVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KIROVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KOSTROMSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KURGANSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_KURSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_LENINGRADSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_LIPETSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_MAGADANSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_MOSKOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_MURMANSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_NIZHEGORODSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_NOVGORODSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_NOVOSIBIRSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_OMSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_ORENBURGSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_ORLOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_PENZENSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_PSKOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_ROSTOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_RYAZANSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_SAKHALINSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_SAMARSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_SARATOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_SMOLENSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_SVERDLOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_TAMBOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_TOMSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_TULSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_TVERSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_TYUMENSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_ULYANOVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_VLADIMIRSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_VOLGOGRADSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_VOLOGODSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_VORONEZHSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_YAROSLAVSKAYA_OBLAST,
        self::RUSSIAN_FEDERATION_MOSKVA,
        self::RUSSIAN_FEDERATION_SANKT_PETERBURG,
        self::RUSSIAN_FEDERATION_YEVREYSKAYA_AVTONOMNAYA_OBLAST,
        self::RUSSIAN_FEDERATION_CHUKOTSKIY_AVTONOMNYY_OKRUG,
        self::RUSSIAN_FEDERATION_KHANTY_MANSIYSKIY_AVTONOMNYY_OKRUG_YUGRA,
        self::RUSSIAN_FEDERATION_NENETSKIY_AVTONOMNYY_OKRUG,
        self::RUSSIAN_FEDERATION_YAMALO_NENETSKIY_AVTONOMNYY_OKRUG,
    ];
}